"""Astro frontend emitter — MVP.

Produces a static Astro project in place of the default Vite/React-Router SPA
when ``rx.Config(frontend_target="astro")`` is set. Scope is intentionally
limited to fully-static pages (no ``rx.State`` usage, no event handlers,
no ``rx.cond`` / ``rx.foreach``) — enough to render ``examples/landing_page``
end-to-end with zero shipped JavaScript.

The emitter reuses the existing component-tree rendering pipeline:
``Component._get_all_imports()`` and ``_RenderUtils.render(component.render())``
produce a JSX string; we wrap it in a React function component and a thin
``.astro`` page. Astro's ``@astrojs/react`` integration renders React
components at build time (no ``client:*`` directive ⇒ static HTML, zero JS).
"""

from __future__ import annotations

import json
import re
from typing import TYPE_CHECKING

from reflex_base import constants
from reflex_base.compiler import templates
from reflex.compiler import utils

if TYPE_CHECKING:
    from reflex_base.components.component import BaseComponent


# Imports we deliberately strip from the generated .tsx: they refer to
# state/router plumbing we don't emit for Astro MVP. For symbols that the
# rendered JSX still references (e.g. react-router's Link), we substitute
# local stubs instead of stripping the import (see _IMPORT_STUBS below).
_DROP_IMPORT_PREFIXES = (
    "$/utils/context",
    "$/utils/state",
    "$/utils/stateful_components",
    "$/utils/components",
)


# Modules we replace with local stubs. Values are a dict of symbol -> stub body.
# The rendered JSX keeps referring to the original symbol names; the stub makes
# that a no-op plain DOM element so no hydration / router plumbing is required.
_IMPORT_STUBS: dict[str, dict[str, str]] = {
    "react-router": {
        # Maps `<Link to="#foo">` to a plain anchor.
        "Link as ReactRouterLink": (
            'const ReactRouterLink = ({to, children, ...rest}) => '
            'jsx("a", {href: to, ...rest}, children);'
        ),
        "NavLink as ReactRouterNavLink": (
            'const ReactRouterNavLink = ({to, children, ...rest}) => '
            'jsx("a", {href: to, ...rest}, children);'
        ),
    },
}


def _astro_package_json(app_name: str) -> str:
    return json.dumps(
        {
            "name": app_name,
            "private": True,
            "type": "module",
            "scripts": {
                "dev": "astro dev --host 0.0.0.0",
                "build": "astro build",
                "export": "astro build",
                "preview": "astro preview",
            },
            "dependencies": {
                "astro": "^4.16.0",
                "@astrojs/react": "^3.6.2",
                "react": "^18.3.1",
                "react-dom": "^18.3.1",
                "@types/react": "^18.3.11",
                "@types/react-dom": "^18.3.1",
                "@emotion/react": "^11.13.3",
                "@radix-ui/themes": "^3.1.4",
                "lucide-react": "^0.453.0",
            },
        },
        indent=2,
    )


def _astro_config() -> str:
    # In output: 'static' mode Astro writes everything to outDir. Reflex's
    # post-build pipeline (reflex/utils/build.py) reads from .web/build/client,
    # so point outDir there directly.
    static_dir = constants.Dirs.STATIC
    return f"""import {{ defineConfig }} from 'astro/config';
import react from '@astrojs/react';

// No adapter = server mode is structurally impossible. outDir matches
// constants.Dirs.STATIC ({static_dir!r}) so reflex run/export find the
// built artifact in the expected place.
export default defineConfig({{
  output: 'static',
  outDir: './{static_dir}',
  integrations: [react()],
  server: {{
    host: '0.0.0.0',
  }},
}});
"""


def _astro_tsconfig() -> str:
    return json.dumps(
        {
            "extends": "astro/tsconfigs/strict",
            "compilerOptions": {
                "jsx": "react-jsx",
                "jsxImportSource": "@emotion/react",
            },
        },
        indent=2,
    )


def _astro_global_css() -> str:
    return """/* Generated by Reflex astro emitter. */
html, body {
  margin: 0;
  padding: 0;
  min-height: 100vh;
}
body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
}
"""


def _theme_toggle_component() -> str:
    """A hand-written island — the smallest possible demonstration of the
    islands architecture. Subscribes to the `<html>` element's class via a
    MutationObserver (DOM-as-store), re-renders when theme changes, writes
    back on click. No reflex runtime needed because the state is a single
    bit living in the DOM.
    """
    return """import { useSyncExternalStore } from 'react';

// Subscribe to class changes on <html>. Everything driven off the class the
// inline theme-init script sets before paint, so SSR and first-paint agree.
const subscribe = (callback: () => void) => {
  const observer = new MutationObserver(callback);
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['class'],
  });
  return () => observer.disconnect();
};

const getSnapshot = () =>
  document.documentElement.classList.contains('dark') ? 'dark' : 'light';

// Server snapshot: matches what the inline script will set once JS runs.
const getServerSnapshot = () => 'light' as const;

export default function ThemeToggle() {
  const theme = useSyncExternalStore(subscribe, getSnapshot, getServerSnapshot);
  const isDark = theme === 'dark';

  const toggle = () => {
    const next = isDark ? 'light' : 'dark';
    const el = document.documentElement;
    el.classList.toggle('dark', next === 'dark');
    el.classList.toggle('light', next === 'light');
    try {
      localStorage.setItem('theme', next);
    } catch {
      /* incognito or storage quota exceeded: ignore */
    }
  };

  return (
    <button
      type="button"
      onClick={toggle}
      aria-label={`Switch to ${isDark ? 'light' : 'dark'} theme`}
      style={{
        position: 'fixed',
        bottom: '16px',
        right: '16px',
        zIndex: 999,
        width: '40px',
        height: '40px',
        borderRadius: '50%',
        border: '1px solid var(--gray-a6)',
        background: 'var(--color-panel-solid)',
        color: 'var(--gray-12)',
        cursor: 'pointer',
        fontSize: '18px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
      }}
    >
      {isDark ? '☀' : '☽'}
    </button>
  );
}
"""


_IMPORT_LINE = re.compile(r'^\s*import\s+.+?\s+from\s+"(?P<src>[^"]+)";?\s*$')


def _rewrite_imports(tsx: str) -> tuple[str, list[str]]:
    """Strip state-plumbing imports; convert stubbed libs into local consts.

    Returns the rewritten tsx and a list of stub declarations to prepend to
    the function body before the `return`.
    """
    kept: list[str] = []
    stubs: list[str] = []
    for line in tsx.splitlines():
        m = _IMPORT_LINE.match(line)
        if not m:
            kept.append(line)
            continue
        src = m.group("src")
        if any(src.startswith(p) for p in _DROP_IMPORT_PREFIXES):
            continue
        if src in _IMPORT_STUBS:
            # Drop the import line; emit stubs for any requested symbols.
            for symbol, body in _IMPORT_STUBS[src].items():
                if symbol in line:
                    stubs.append(body)
            continue
        kept.append(line)
    return "\n".join(kept), stubs


def _route_module_name(route: str) -> str:
    """Map a Reflex route string to a TSX module stem + Astro page path."""
    if route in ("", "index"):
        return "index"
    # Preserve dynamic segments verbatim; Astro accepts [param].astro too.
    return route.strip("/").replace("/", "_") or "index"


def _compile_page_component(route: str, component: "BaseComponent") -> tuple[str, str]:
    """Render a Reflex page as a standalone React function component file."""
    from reflex.compiler.compiler import _apply_common_imports

    imports = component._get_all_imports()
    _apply_common_imports(imports)
    imports = utils.compile_imports(imports)

    hooks = component._get_all_hooks()
    custom_codes = component._get_all_custom_code()

    imports_str = "\n".join(
        templates._RenderUtils.get_import(imp) for imp in imports
    )

    rendered = templates._RenderUtils.render(component.render())
    hooks_body = templates._render_hooks(hooks)
    module_name = _route_module_name(route)
    component_name = f"Page_{module_name}"

    # First-pass tsx — still contains raw import lines.
    tsx = f"""/* Auto-generated by Reflex astro emitter. Do not edit by hand. */
{imports_str}

{chr(10).join(custom_codes)}

export default function {component_name}() {{
__ASTRO_STUBS__
  // refs bag is used by rx.html refs; kept as a local so stripped imports
  // from $/utils/components don't break references in the render tree.
  const refs = {{}};
{hooks_body}

  return (
    {rendered}
  );
}}
"""
    tsx, stubs = _rewrite_imports(tsx)
    stubs_block = "\n".join(f"  {s}" for s in stubs)
    tsx = tsx.replace("__ASTRO_STUBS__", stubs_block)

    return (
        f"src/components/{module_name}.tsx",
        tsx,
    )


_THEME_PROP_NAMES = (
    "accent_color",
    "gray_color",
    "radius",
    "scaling",
    "panel_background",
    "has_background",
)


def _extract_theme_props(theme_component: "BaseComponent | None") -> dict[str, str]:
    """Pull literal theme props off the app's Theme component.

    Reflex defaults `app.theme` to `rx.theme(accent_color="blue")` but the
    astro wrapper uses a plain `<Theme>` from @radix-ui/themes. Without
    mirroring these props, Radix uses its own default (indigo), producing
    HTML whose `data-accent-color` doesn't match the CSS scale we imported
    via get_radix_themes_stylesheets. That mismatch leaves `--accent-9` and
    friends undefined, which is the washed-out / gray look.
    """
    if theme_component is None:
        return {}
    from reflex.compiler.compiler import _extract_literal_prop

    result: dict[str, str] = {}
    for name in _THEME_PROP_NAMES:
        if not hasattr(theme_component, name):
            continue
        literal = _extract_literal_prop(theme_component, name)
        if literal is None:
            continue
        # Normalize boolean-like props to the `{true}` / `{false}` JSX form.
        if isinstance(literal, bool):
            result[name] = "true" if literal else "false"
        else:
            result[name] = str(literal)
    return result


def _theme_props_to_jsx(props: dict[str, str]) -> str:
    """Serialize extracted theme props to attributes for the astro Theme tag."""
    # Translate snake_case Python names to the camelCase prop names the Radix
    # React component expects. Boolean-like props use the JSX `{true}` form.
    camel = {
        "accent_color": "accentColor",
        "gray_color": "grayColor",
        "radius": "radius",
        "scaling": "scaling",
        "panel_background": "panelBackground",
        "has_background": "hasBackground",
    }
    parts = []
    for py_name, value in props.items():
        jsx_name = camel.get(py_name, py_name)
        if value in ("true", "false"):
            parts.append(f"{jsx_name}={{{value}}}")
        else:
            parts.append(f'{jsx_name}="{value}"')
    return " ".join(parts)


def _astro_page_wrapper(
    route: str,
    title: str,
    description: str,
    radix_stylesheets: list[str],
    theme_props: dict[str, str] | None = None,
) -> tuple[str, str]:
    """Emit the thin .astro file that imports the React component."""
    module_name = _route_module_name(route)
    component_name = f"Page_{module_name}"

    astro_route = "index" if route in ("", "index") else route.strip("/")
    astro_path = f"src/pages/{astro_route}.astro"

    safe_title = title.replace('"', '\\"') if title else "Reflex"
    safe_description = (
        description.replace('"', '\\"') if description else ""
    )

    # Granular Radix stylesheets ship only the color scales actually referenced
    # by Theme components in the page tree; see get_radix_themes_stylesheets.
    radix_imports = "\n".join(f"import '{s}';" for s in radix_stylesheets)

    # Inline theme-init script: runs synchronously before body paints so there's
    # no flash of wrong theme. Reads localStorage first, falls back to OS
    # preference. Sets `light`/`dark` class on <html> so <Theme appearance="inherit">
    # picks it up. This is the standard Astro theme-init pattern.
    theme_init = """<script is:inline>
      (() => {
        const stored = localStorage.getItem('theme');
        const dark = stored === 'dark' || (!stored && matchMedia('(prefers-color-scheme: dark)').matches);
        document.documentElement.classList.toggle('dark', dark);
        document.documentElement.classList.toggle('light', !dark);
      })();
    </script>"""

    theme_attrs = _theme_props_to_jsx(theme_props or {})
    theme_attrs = (" " + theme_attrs) if theme_attrs else ""

    content = f"""---
{radix_imports}
import '../styles/global.css';
import {{ Theme }} from '@radix-ui/themes';
import {component_name} from '../components/{module_name}';
import ThemeToggle from '../components/ThemeToggle';
---
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{safe_title}</title>
    <meta name="description" content="{safe_description}" />
    {theme_init}
  </head>
  <body>
    <Theme appearance="inherit"{theme_attrs}>
      <{component_name} />
      <ThemeToggle client:load />
    </Theme>
  </body>
</html>
"""
    return astro_path, content


_COMPRESS_HELPERS = (
    "compress-static.js",
    "vite-plugin-compress.js",
    "vite-plugin-utils.js",
)


def _compression_helpers() -> list[tuple[str, str]]:
    """Ship the precompression helper scripts alongside the Astro output.

    Astro doesn't pre-gzip/brotli its assets; reflex's post-build step
    (_compress_static_output) shells out to compress-static.js to emit .gz/.br
    sidecars so static hosts serve them directly.
    """
    from reflex_base.constants.base import Templates

    template_dir = __import__("pathlib").Path(Templates.Dirs.WEB_TEMPLATE)
    results: list[tuple[str, str]] = []
    for name in _COMPRESS_HELPERS:
        source = template_dir / name
        if source.exists():
            results.append((name, source.read_text()))
    return results


def install_dependencies() -> None:
    """Run npm install in the web dir after astro files have been written.

    Idempotent: if node_modules/.package-lock.json looks up-to-date with
    package.json, npm install exits fast.
    """
    import subprocess

    from reflex.utils import console
    from reflex.utils.prerequisites import get_web_dir

    web_dir = get_web_dir()
    pkg_json = web_dir / "package.json"
    if not pkg_json.exists():
        return

    console.log("Installing astro frontend dependencies (npm install).")
    try:
        subprocess.run(
            ["npm", "install", "--legacy-peer-deps", "--no-audit", "--no-fund"],
            cwd=web_dir,
            check=True,
        )
    except FileNotFoundError:
        console.error(
            "npm not found on PATH. Install Node.js to use the astro frontend "
            "target, or run `npm install` manually inside .web/."
        )
    except subprocess.CalledProcessError as exc:
        console.error(f"npm install failed with exit code {exc.returncode}.")
        raise


def compile_astro_project(
    pages: "dict[str, BaseComponent]",
    page_meta: dict[str, dict[str, str]],
    app_name: str,
    theme_roots: "list | None" = None,
    theme_component: "BaseComponent | None" = None,
) -> list[tuple[str, str]]:
    """Emit all files for a standalone Astro project.

    Args:
        pages: Rendered component per route (from ``App._pages``).
        page_meta: Per-route metadata (``title`` and ``description``) collected
            from ``app.add_page``.
        app_name: Used as the package name in package.json.
        theme_roots: Root components used to discover which Radix color scales
            are actually referenced, so we can ship only the stylesheets we need
            instead of the 695 KB monolithic @radix-ui/themes/styles.css.

    Returns:
        List of (path, content) tuples relative to the web working dir.
    """
    from reflex.compiler.compiler import get_radix_themes_stylesheets

    radix_stylesheets = get_radix_themes_stylesheets(theme_roots or [])
    theme_props = _extract_theme_props(theme_component)

    results: list[tuple[str, str]] = [
        ("package.json", _astro_package_json(app_name)),
        ("astro.config.mjs", _astro_config()),
        ("tsconfig.json", _astro_tsconfig()),
        (f"src/{constants.Dirs.STYLES}/global.css", _astro_global_css()),
        # Hand-written island — proof-of-concept for Depth-2 islands.
        # See _theme_toggle_component for the architecture rationale.
        ("src/components/ThemeToggle.tsx", _theme_toggle_component()),
        *_compression_helpers(),
    ]

    for route, component in pages.items():
        results.append(_compile_page_component(route, component))
        meta = page_meta.get(route, {})
        results.append(
            _astro_page_wrapper(
                route,
                title=meta.get("title", ""),
                description=meta.get("description", ""),
                radix_stylesheets=radix_stylesheets,
                theme_props=theme_props,
            )
        )

    return results
