"""Auto-generated by Reflex Notebooks on 2026-05-22T23:09:31.

This is a starting point. Edit freely — once you check it in you have a normal Reflex app.
"""

from __future__ import annotations

import reflex as rx


class State(rx.State):
    """Notebook state derived from input widgets."""

    region: str = 'All'
    product: str = 'Gizmo'
    min_revenue: float = 200
    sales_on_after: str = '2025-02-01'
    customer_contains: str = ''
    show_totals: bool = True
    pick_a_random_row: int = 0

    @rx.event
    def set_region(self, value: str):
        """Update region from the bound widget."""
        self.region = value

    @rx.event
    def set_product(self, value: str):
        """Update product from the bound widget."""
        self.product = value

    @rx.event
    def set_min_revenue(self, value: list[float]):
        """Update min_revenue from the bound slider."""
        self.min_revenue = value[0]

    @rx.event
    def set_sales_on_after(self, value: str):
        """Update sales_on_after from the bound widget."""
        self.sales_on_after = value

    @rx.event
    def set_customer_contains(self, value: str):
        """Update customer_contains from the bound widget."""
        self.customer_contains = value

    @rx.event
    def set_show_totals(self, value: bool):
        """Update show_totals from the bound widget."""
        self.show_totals = value

    @rx.event
    def set_pick_a_random_row(self, value: int):
        """Update pick_a_random_row from the bound widget."""
        self.pick_a_random_row = value


def index() -> rx.Component:
    """The deployed notebook page."""
    return rx.vstack(
        rx.select(['All', 'East', 'North', 'South', 'West'], value=State.region, on_change=State.set_region, placeholder='Region'),
        rx.select(['All', 'Gadget', 'Gizmo', 'Sprocket', 'Widget'], value=State.product, on_change=State.set_product, placeholder='Product'),
        rx.slider(value=[State.min_revenue], on_change=State.set_min_revenue, min=0, max=1500, step=50),
        rx.input(type="date", value=State.sales_on_after, on_change=State.set_sales_on_after),
        rx.input(value=State.customer_contains, on_change=State.set_customer_contains, placeholder='e.g. Acme'),
        rx.checkbox('Show totals', checked=State.show_totals, on_change=State.set_show_totals),
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.box(),  # unsupported output
        rx.html(''),  # placeholder for HTML output
        rx.image(src=''),  # placeholder for matplotlib figure
        rx.plotly(),  # placeholder for plotly figure
        rx.box(),  # unsupported output
        rx.button('Pick a random row', on_click=State.set_pick_a_random_row(State.pick_a_random_row + 1)),
        rx.html(''),  # placeholder for HTML output
        spacing="4",
        padding="2em",
    )

app = rx.App()
app.add_page(index, title='sales_dashboard')
