"""JavaScript templates that wire the frontend inspector into the dev server.

The plugin only injects a ``<script>`` tag and registers the editor middleware;
all interactive logic lives in :file:`reflex_base/assets/inspector/inspector.js`.
"""

from __future__ import annotations

import json

from reflex_base.inspector.shortcut import Shortcut


def _shortcut_literal(shortcut: Shortcut) -> str:
    """Render a :class:`Shortcut` as a JSON object literal.

    Args:
        shortcut: The parsed shortcut to embed in the generated JS.

    Returns:
        A JSON-formatted object literal suitable for inclusion in JS source.
    """
    return json.dumps({
        "key": shortcut.key,
        "alt": shortcut.alt,
        "ctrl": shortcut.ctrl,
        "meta": shortcut.meta,
        "shift": shortcut.shift,
    })


def vite_plugin_template(shortcut: Shortcut, force: bool) -> str:
    """Render a Vite plugin that mounts the inspector during ``vite dev``.

    The plugin:
      - injects ``<script src="/__reflex/inspector.js" type="module">`` and a
        small ``window.__REFLEX_INSPECTOR_CONFIG__`` literal into ``index.html``;
      - registers the ``launch-editor`` middleware on the dev server;
      - is gated on ``apply: 'serve'`` unless ``force`` is true (matching the
        ``"force"`` config mode).

    Args:
        shortcut: The keyboard shortcut to surface to the browser script.
        force: If True, the plugin runs in build mode too (``"force"`` config).

    Returns:
        The plugin source code as a string.
    """
    apply_clause = "" if force else "  apply: 'serve',\n"
    shortcut_literal = _shortcut_literal(shortcut)
    return rf"""// Auto-generated by Reflex frontend inspector. Do not edit.
import reflexEditorMiddleware from "./public/__reflex/dev_server_middleware.js";

const REFLEX_INSPECTOR_CONFIG = {shortcut_literal};

export default function reflexInspectorPlugin() {{
  return {{
    name: "reflex-frontend-inspector",
{apply_clause}    transformIndexHtml() {{
      return [
        {{
          tag: "script",
          attrs: {{ type: "module" }},
          children:
            "window.__REFLEX_INSPECTOR_CONFIG__ = " +
            JSON.stringify(REFLEX_INSPECTOR_CONFIG) + ";",
          injectTo: "head",
        }},
        {{
          tag: "script",
          attrs: {{ type: "module", src: "/__reflex/inspector.js" }},
          injectTo: "head",
        }},
      ];
    }},
    configureServer(server) {{
      server.middlewares.use(reflexEditorMiddleware);
    }},
  }};
}}
"""


def astro_integration_template(shortcut: Shortcut, force: bool) -> str:
    """Render an Astro integration that mounts the inspector during ``astro dev``.

    Args:
        shortcut: The keyboard shortcut to surface to the browser script.
        force: If True, the integration also activates in non-dev commands
            (``"force"`` config mode).

    Returns:
        The integration source code as a string.
    """
    shortcut_literal = _shortcut_literal(shortcut)
    dev_only_guard = "" if force else "        if (command !== 'dev') return;\n"
    return rf"""// Auto-generated by Reflex frontend inspector. Do not edit.
import reflexEditorMiddleware from "./public/__reflex/dev_server_middleware.js";

const REFLEX_INSPECTOR_CONFIG = {shortcut_literal};

export default function reflexInspectorIntegration() {{
  return {{
    name: "reflex-frontend-inspector",
    hooks: {{
      "astro:config:setup": ({{ command, injectScript }}) => {{
{dev_only_guard}        injectScript(
          "head-inline",
          "window.__REFLEX_INSPECTOR_CONFIG__ = " +
            JSON.stringify({shortcut_literal}) +
            ";import('/__reflex/inspector.js');",
        );
      }},
      "astro:server:setup": ({{ server }}) => {{
        server.middlewares.use(reflexEditorMiddleware);
      }},
    }},
  }};
}}
"""
