"""JavaScript templates that wire the frontend inspector into the dev server.

The browser-facing ``<script>`` tags are injected at the document-root level by
``reflex.compiler.utils._inspector_head_components`` (React Router 7 renders
HTML through React, so Vite's ``transformIndexHtml`` does not fire for app
routes). The plugin therefore only registers the dev-server middleware that
launches the user's editor on click.
"""

from __future__ import annotations

import json

from reflex_base.inspector import PUBLIC_DIRNAME


def vite_plugin_template(editor: str = "") -> str:
    """Render a Vite plugin that mounts the inspector dev-server middleware.

    Args:
        editor: Editor invocation forwarded to ``launch-editor`` via
            ``process.env.REFLEX_EDITOR``. Empty string defers to the user's
            existing ``REFLEX_EDITOR``/``VISUAL``/``EDITOR`` env vars.

    Returns:
        The plugin source code as a string.
    """
    editor_literal = json.dumps(editor)
    editor_clause = (
        f"      process.env.REFLEX_EDITOR ||= {editor_literal};\n" if editor else ""
    )
    return rf"""// Auto-generated by Reflex frontend inspector. Do not edit.
import reflexEditorMiddleware from "./public/{PUBLIC_DIRNAME}/dev_server_middleware.js";

export default function reflexInspectorPlugin() {{
  return {{
    name: "reflex-frontend-inspector",
    apply: 'serve',
    configureServer(server) {{
{editor_clause}      server.middlewares.use(reflexEditorMiddleware);
    }},
  }};
}}
"""
