"""Per-target router adapter templates.

The shared runtime in ``state.js`` must not import React Router directly.
Each target supplies a ``$/utils/router_adapter.js`` that exposes one React
hook with a stable contract:

    useRouterAdapter() -> {
      location: { pathname, search, hash, state },
      navigate: (path, opts?) => void,
      params: Record<string, string>,
      searchParams: URLSearchParams,
    }

The React Router target wraps React Router hooks (current behavior). The
Astro target uses ``window.location`` + ``history.pushState`` + ``popstate``
so it never imports ``react-router`` and SSR succeeds without a ``<Router>``
ancestor. Both adapters return SSR-safe defaults when ``window`` is
undefined so ``state.js``'s ``useEventLoop`` can be evaluated server-side.
"""

from __future__ import annotations

from functools import cache


@cache
def react_router_adapter_template() -> str:
    """Render ``$/utils/router_adapter.js`` for the React Router target.

    Returns:
        The JS source. Wraps React Router's ``useLocation`` /
        ``useNavigate`` / ``useParams`` / ``useSearchParams`` so the shared
        runtime can stay router-agnostic.
    """
    return r"""// Generated by Reflex (frontend_target="react_router"). Do not edit.
import {
  useLocation,
  useNavigate,
  useParams,
  useSearchParams,
} from "react-router";

export const useRouterAdapter = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const params = useParams();
  const [searchParams] = useSearchParams();
  return { location, navigate, params, searchParams };
};
"""


@cache
def astro_router_adapter_template() -> str:
    """Render ``$/utils/router_adapter.js`` for the Astro target.

    Implements the router-adapter contract on top of native browser APIs
    (``window.location`` + ``history.pushState`` + the ``popstate`` event).
    The Astro target never imports ``react-router``.

    SSR safety: every browser-only access is gated on
    ``typeof window !== "undefined"`` so the hook returns sensible empty
    defaults during ``astro build``'s server-render pass. Once the page
    hydrates, ``useEffect`` re-reads ``window.location`` and switches the
    component into client mode.

    Returns:
        The JS source.
    """
    return r"""// Generated by Reflex (frontend_target="astro"). Do not edit.
import { useCallback, useEffect, useState } from "react";

const _IS_SERVER = typeof window === "undefined";

const _readLocation = () => {
  if (_IS_SERVER) {
    return { pathname: "/", search: "", hash: "", state: null };
  }
  return {
    pathname: window.location.pathname,
    search: window.location.search,
    hash: window.location.hash,
    state: window.history.state,
  };
};

// Reflex injects compile-time route params via Astro.params on the .astro
// page; the page-root island reads them off ``window.__REFLEX_ROUTER__``
// which the .astro file populates inside an ``is:inline`` script.
const _readParams = () => {
  if (_IS_SERVER) return {};
  const r = window.__REFLEX_ROUTER__ || {};
  return r.params || {};
};

const _readSearchParams = () => {
  if (_IS_SERVER) return new URLSearchParams("");
  return new URLSearchParams(window.location.search);
};

export const useRouterAdapter = () => {
  const [location, setLocation] = useState(_readLocation);
  const [searchParams, setSearchParams] = useState(_readSearchParams);

  useEffect(() => {
    if (_IS_SERVER) return undefined;
    const sync = () => {
      setLocation(_readLocation());
      setSearchParams(_readSearchParams());
    };
    // popstate covers back/forward; we also intercept pushState/replaceState
    // by patching them once so SPA-style navigations trigger re-renders.
    window.addEventListener("popstate", sync);
    if (!window.__REFLEX_HISTORY_PATCHED__) {
      window.__REFLEX_HISTORY_PATCHED__ = true;
      const pushState = window.history.pushState.bind(window.history);
      const replaceState = window.history.replaceState.bind(window.history);
      window.history.pushState = function (...args) {
        const r = pushState(...args);
        window.dispatchEvent(new Event("popstate"));
        return r;
      };
      window.history.replaceState = function (...args) {
        const r = replaceState(...args);
        window.dispatchEvent(new Event("popstate"));
        return r;
      };
    }
    return () => {
      window.removeEventListener("popstate", sync);
    };
  }, []);

  const navigate = useCallback((path, opts = {}) => {
    if (_IS_SERVER) return;
    if (opts.replace) {
      window.history.replaceState(opts.state ?? null, "", path);
    } else {
      window.history.pushState(opts.state ?? null, "", path);
    }
  }, []);

  return { location, navigate, params: _readParams(), searchParams };
};
"""


def router_adapter_template_for(target: str) -> str:
    """Pick the right router adapter source for ``target``.

    Args:
        target: The frontend target name. One of ``"react_router"`` or
            ``"astro"``.

    Returns:
        The JS source.

    Raises:
        ValueError: If the target is not recognized.
    """
    if target == "react_router":
        return react_router_adapter_template()
    if target == "astro":
        return astro_router_adapter_template()
    msg = f"Unknown frontend_target={target!r}. Expected 'react_router' or 'astro'."
    raise ValueError(msg)
