"""Generated Zustand store + hook helpers for the shared runtime.

The runtime replaces the four React Contexts (state / dispatch / event-loop
/ uploads / color-mode) with a module-singleton Zustand store. The React
Router target keeps its ``context.js`` compatibility shell — rewritten to
delegate to this store so call sites that import from ``$/utils/context``
continue to work. The Astro target imports the new hooks directly.

This module is pure-string codegen. The generated JS does not import any
Reflex-specific module beyond ``zustand`` itself, so it can ship on either
target without further rewiring.
"""

from __future__ import annotations

from functools import cache


@cache
def zustand_store_template() -> str:
    """Render ``$/utils/store.js`` — the Zustand store + helper hooks.

    The store has named slices that map 1:1 to the React Contexts they
    replace. ``applyDelta`` performs a single atomic ``set((s) => ...)`` so
    subscribers see one commit per backend delta even when multiple state
    slices are touched.

    Returns:
        The full ``store.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
//
// Module-singleton Zustand store backing the shared runtime. The React
// Router target's `context.js` and the Astro target's per-page islands
// both subscribe to this store, so backend deltas commit once and every
// hydrated React root sees the same snapshot.
import { create } from "zustand";

const noop = () => {};

// Color-mode persistence + DOM wiring lives here so islands work without
// mounting a React provider. `RadixThemesColorModeProvider` (app mode)
// can still call `setReflexColorMode(...)` to override these defaults;
// its values then shadow ours, no behavior change for app mode.
const COLOR_MODE_COOKIE = "reflex-color-mode";
const COLOR_MODE_STORAGE_KEY = "color_mode";
const COLOR_MODE_COOKIE_MAX_AGE = 60 * 60 * 24 * 365;

const _hasWindow = typeof window !== "undefined";
const _hasDocument = typeof document !== "undefined";

const _readCookieColorMode = () => {
  if (!_hasDocument) return null;
  const match = document.cookie.match(
    new RegExp("(^|;\\s*)" + COLOR_MODE_COOKIE + "=([^;]+)"),
  );
  return match ? decodeURIComponent(match[2]) : null;
};

const _readStorageColorMode = () => {
  if (!_hasWindow) return null;
  try {
    return window.localStorage.getItem(COLOR_MODE_STORAGE_KEY);
  } catch (e) {
    return null;
  }
};

const _writeCookieColorMode = (mode) => {
  if (!_hasDocument) return;
  document.cookie =
    COLOR_MODE_COOKIE +
    "=" +
    encodeURIComponent(mode) +
    "; path=/; max-age=" +
    COLOR_MODE_COOKIE_MAX_AGE +
    "; SameSite=Lax";
};

const _writeStorageColorMode = (mode) => {
  if (!_hasWindow) return;
  try {
    window.localStorage.setItem(COLOR_MODE_STORAGE_KEY, mode);
  } catch (e) {}
};

const _systemPrefersDark = () =>
  _hasWindow &&
  window.matchMedia("(prefers-color-scheme: dark)").matches;

const _resolveColorMode = (mode) =>
  mode === "system" ? (_systemPrefersDark() ? "dark" : "light") : mode;

const _applyColorModeToDOM = (resolved) => {
  if (!_hasDocument) return;
  const root = document.documentElement;
  root.classList.remove("light", "dark");
  root.classList.add(resolved);
  root.setAttribute("data-color-mode", resolved);
  // Hint the UA so form controls pick the right palette too.
  root.style.colorScheme = resolved;
};

const _initialRawColorMode = (() => {
  const fromCookie = _readCookieColorMode();
  if (fromCookie) return fromCookie;
  const fromStorage = _readStorageColorMode();
  if (fromStorage) return fromStorage;
  return "system";
})();

const _commitColorMode = (mode) => {
  const resolved = _resolveColorMode(mode);
  _applyColorModeToDOM(resolved);
  _writeCookieColorMode(mode);
  _writeStorageColorMode(mode);
  useReflexStore.getState().setColorMode({
    rawColorMode: mode,
    colorMode: mode,
    resolvedColorMode: resolved,
    toggleColorMode: () =>
      _commitColorMode(resolved === "light" ? "dark" : "light"),
    setColorMode: _commitColorMode,
  });
};

const initialColorMode = {
  rawColorMode: _initialRawColorMode,
  colorMode: _initialRawColorMode,
  resolvedColorMode: _resolveColorMode(_initialRawColorMode),
  toggleColorMode: () => {
    const current = _resolveColorMode(
      useReflexStore.getState().colorMode.rawColorMode,
    );
    _commitColorMode(current === "light" ? "dark" : "light");
  },
  setColorMode: (mode) => _commitColorMode(mode),
};

// Keep `system` mode in sync with OS-level preference changes. Only fires
// when the user has not pinned a specific mode.
if (_hasWindow && window.matchMedia) {
  window
    .matchMedia("(prefers-color-scheme: dark)")
    .addEventListener("change", () => {
      const slice = useReflexStore.getState().colorMode;
      if (slice.rawColorMode !== "system") return;
      _commitColorMode("system");
    });
}

// Local handler for events that don't need a backend round-trip. Lets
// islands-mode pages (which never register a real event-loop adapter)
// still dispatch ``rx.call_script``, ``set_color_mode``, and other
// front-end-only events. ``state.js`` registers a fuller adapter in app
// mode; that one shadows this one but still includes the same local
// handling, so behavior in app mode is unchanged.
const _runLocalEvent = async (event) => {
  if (!event || !event.name) return;
  const payload = event.payload || {};
  if (event.name === "_call_function") {
    try {
      const fn =
        typeof payload.function === "string"
          ? eval(payload.function)
          : payload.function;
      if (typeof fn !== "function") return;
      const result = fn();
      const finalResult =
        result && typeof result.then === "function" ? await result : result;
      if (payload.callback) {
        const cb =
          typeof payload.callback === "string"
            ? eval(payload.callback)
            : payload.callback;
        if (typeof cb === "function") cb(finalResult);
      }
    } catch (e) {
      // Surface to the console; islands mode has no error-boundary host
      // to forward to.
      // eslint-disable-next-line no-console
      console.error("[reflex] _call_function failed:", e);
    }
    return;
  }
  if (event.name === "_call_script") {
    try {
      const result = eval(payload.javascript_code);
      const finalResult =
        result && typeof result.then === "function" ? await result : result;
      if (payload.callback) {
        const cb =
          typeof payload.callback === "string"
            ? eval(payload.callback)
            : payload.callback;
        if (typeof cb === "function") cb(finalResult);
      }
    } catch (e) {
      // eslint-disable-next-line no-console
      console.error("[reflex] _call_script failed:", e);
    }
    return;
  }
  // Backend / framework events (``_redirect``, state mutations, etc.) need
  // the full adapter from ``state.js``. Silently drop them in islands mode
  // — there's no socket to forward them to.
};

const _localAddEvents = (events, _args, _actions) => {
  if (!Array.isArray(events)) return;
  for (const event of events) {
    // Fire and forget; each event handler is independent.
    void _runLocalEvent(event);
  }
};

const initialEventLoop = {
  addEvents: _localAddEvents,
  connectErrors: [],
  isHydrated: false,
};

export const useReflexStore = create((set, get) => ({
  // Per-state slice of backend-mirrored values.
  state: {},
  // Per-state dispatcher functions (state slice -> (delta) => void).
  dispatch: {},
  // Event-loop adapter set by the React/Astro entrypoint.
  eventLoop: initialEventLoop,
  // File uploads, keyed by upload component id.
  uploads: {},
  // Resolved color mode plus its setters.
  colorMode: initialColorMode,

  // Apply an atomic backend delta. `delta` is `{ [stateName]: partial }`.
  // One `set` call so subscribers see exactly one commit per delta.
  applyDelta: (delta) =>
    set((prev) => {
      const next = { ...prev.state };
      for (const stateName of Object.keys(delta || {})) {
        const patch = delta[stateName];
        if (patch == null) continue;
        next[stateName] = { ...(prev.state[stateName] || {}), ...patch };
      }
      return { state: next };
    }),

  // Replace a state slice in full (used by HYDRATE).
  setStateSlice: (stateName, value) =>
    set((prev) => ({ state: { ...prev.state, [stateName]: value } })),

  // Register a per-state dispatcher (typically wired by the legacy reducer
  // shim in `context.js`).
  registerDispatch: (stateName, fn) =>
    set((prev) => ({ dispatch: { ...prev.dispatch, [stateName]: fn } })),

  // Replace the event-loop slice (the Astro entrypoint calls this once per
  // page; the React Router shim calls it inside `useEventLoop`).
  setEventLoop: (eventLoop) => set({ eventLoop }),

  // Update an upload slot.
  setUploads: (componentId, files) =>
    set((prev) => ({
      uploads: { ...prev.uploads, [componentId]: files },
    })),

  setUploadsByUpdater: (updater) =>
    set((prev) => {
      const next =
        typeof updater === "function" ? updater(prev.uploads) : updater;
      return { uploads: next || {} };
    }),

  clearUploads: (componentId) =>
    set((prev) => {
      const next = { ...prev.uploads };
      delete next[componentId];
      return { uploads: next };
    }),

  setColorMode: (colorMode) => set({ colorMode }),
}));

// Helper hooks. These match the ergonomics of the legacy React Context API.

export const useReflexState = (stateName) => {
  const slice = useReflexStore((s) => s.state[stateName]);
  return slice === undefined
    ? useReflexStore.getState().state[stateName]
    : slice;
};

export const useReflexDispatch = (stateName) => {
  const dispatch = useReflexStore((s) => s.dispatch[stateName]);
  return dispatch === undefined
    ? useReflexStore.getState().dispatch[stateName]
    : dispatch;
};

export const useReflexEventLoop = () => {
  const eventLoop = useReflexStore((s) => s.eventLoop);
  return eventLoop || useReflexStore.getState().eventLoop;
};

export const useReflexUploads = (componentId) => {
  const uploads = useReflexStore((s) => s.uploads[componentId]);
  return uploads ?? useReflexStore.getState().uploads[componentId] ?? [];
};

export const useReflexColorMode = () => {
  const colorMode = useReflexStore((s) => s.colorMode);
  return colorMode || useReflexStore.getState().colorMode;
};

// Imperative accessors (for code that runs outside React, e.g. the Astro
// runtime adapter or the event-loop singleton).
export const getReflexState = (stateName) =>
  useReflexStore.getState().state[stateName];

export const getReflexDispatch = (stateName) =>
  useReflexStore.getState().dispatch[stateName];

export const applyReflexDelta = (delta) =>
  useReflexStore.getState().applyDelta(delta);

export const setReflexEventLoop = (eventLoop) =>
  useReflexStore.getState().setEventLoop(eventLoop);

export const setReflexColorMode = (colorMode) =>
  useReflexStore.getState().setColorMode(colorMode);

export const registerReflexDispatch = (stateName, fn) =>
  useReflexStore.getState().registerDispatch(stateName, fn);

export const getReflexDispatches = () =>
  useReflexStore.getState().dispatch;
"""


@cache
def event_loop_runtime_template() -> str:
    """Render ``$/utils/event_loop.js`` — the target-agnostic event loop adapter.

    The runtime piece exposes a ``createEventLoop(...)`` factory plus a
    module-singleton ``getOrCreateEventLoop(...)`` accessor. The React Router
    target wraps it inside the existing ``useEventLoop`` hook (compatibility
    shell), and the Astro adapter calls it directly when the first stateful
    island hydrates.

    The implementation here is intentionally minimal: it owns the addEvents
    queue and the connectErrors list, and it pushes its slice into the
    shared Zustand store via ``setReflexEventLoop`` so subscribers stay in
    sync. Socket.io wiring still lives in ``state.js``; that module is
    expected to register itself by calling ``setEventLoopAdapter`` once on
    boot. This split lets us extract the rest of ``state.js`` incrementally
    without breaking the React Router target.

    Returns:
        The full ``event_loop.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
//
// Target-agnostic event loop runtime. Owns the addEvents queue, connect
// errors, and hydration flag; the underlying socket lifecycle lives in
// `state.js` (legacy) and registers via `setEventLoopAdapter`.
import {
  applyReflexDelta,
  setReflexEventLoop,
  useReflexStore,
} from "$/utils/store";

let _adapter = {
  addEvents: undefined,
  connectErrors: [],
  isHydrated: false,
};

const _publish = () => {
  setReflexEventLoop({
    addEvents: _adapter.addEvents,
    connectErrors: [..._adapter.connectErrors],
    isHydrated: _adapter.isHydrated,
  });
};

export const setEventLoopAdapter = (next) => {
  _adapter = { ..._adapter, ...next };
  _publish();
};

export const getEventLoopAdapter = () => _adapter;

// Imperative entry the Astro runtime singleton uses to dispatch a chain.
export const dispatchEventChain = (events) => {
  const fn = _adapter.addEvents;
  if (typeof fn !== "function") {
    // Queue inside the adapter until the socket layer has registered its
    // addEvents implementation.
    _adapter.connectErrors = [
      ..._adapter.connectErrors,
      { type: "queue", reason: "no addEvents adapter yet" },
    ];
    _publish();
    return;
  }
  fn(events);
};

// Convenience re-exports so a single module covers both the store and the
// event-loop in callers that need both.
export { applyReflexDelta, useReflexStore };
"""


@cache
def color_mode_inline_setter_template() -> str:
    """Render the ``$/utils/color_mode_inline.js`` head-script helper.

    Used by both targets when generating the inline ``<head>`` script that
    sets the color mode before first paint. Mirrors the Astro layout's
    inline emitter but lives at the Reflex runtime layer so the React
    Router target's `app.html` template can include it too once the React
    runtime stops doing the work itself.

    Returns:
        The full ``color_mode_inline.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
// Synchronous inline head script. Resolves cookie -> localStorage ->
// system preference -> default and applies the color mode to <html>
// before first paint.
export const colorModeInlineScript = ({
  cookieName = "reflex-color-mode",
  storageKey = "color_mode",
  defaultColorMode = "system",
} = {}) => `(function () {
  try {
    var resolved = null;
    var match = document.cookie.match(new RegExp('(^|;\\s*)' + ${JSON.stringify(cookieName)} + '=([^;]+)'));
    if (match) { resolved = decodeURIComponent(match[2]); }
    if (!resolved) {
      try {
        var stored = window.localStorage.getItem(${JSON.stringify(storageKey)});
        if (stored) { resolved = stored; }
      } catch (e) {}
    }
    if (!resolved || resolved === 'system') {
      var fallback = ${JSON.stringify(defaultColorMode)};
      if (fallback === 'system') {
        resolved = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      } else {
        resolved = fallback;
      }
    }
    var root = document.documentElement;
    if (resolved === 'dark') { root.classList.add('dark'); root.classList.remove('light'); }
    else { root.classList.add('light'); root.classList.remove('dark'); }
    root.setAttribute('data-color-mode', resolved);
  } catch (e) {}
})();`;
"""
