"""Generated Zustand store + hook helpers for the shared runtime.

Phase A of the Astro migration replaces the four React Contexts (state /
dispatch / event-loop / uploads / color-mode) with a module-singleton
Zustand store. The React Router target keeps its current ``context.js``
compatibility shell during the migration window — that shell is rewritten
to delegate to this store so call sites that import from ``$/utils/context``
continue to work. The Astro target imports the new hooks directly.

This module is pure-string codegen. The generated JS does not import any
Reflex-specific module beyond ``zustand`` itself, so it can ship on either
target without further rewiring.
"""

from __future__ import annotations


def zustand_store_template() -> str:
    """Render ``$/utils/store.js`` — the Zustand store + helper hooks.

    The store has named slices that map 1:1 to the React Contexts they
    replace. ``applyDelta`` performs a single atomic ``set((s) => ...)`` so
    subscribers see one commit per backend delta even when multiple state
    slices are touched.

    Returns:
        The full ``store.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
//
// Module-singleton Zustand store backing the shared runtime. The React
// Router target's `context.js` and the Astro target's per-page islands
// both subscribe to this store, so backend deltas commit once and every
// hydrated React root sees the same snapshot.
import { create } from "zustand";

const noop = () => {};

const initialColorMode = {
  colorMode: "system",
  resolvedColorMode: "light",
  toggleColorMode: noop,
  setColorMode: noop,
};

const initialEventLoop = {
  addEvents: undefined,
  connectErrors: [],
  isHydrated: false,
};

export const useReflexStore = create((set, get) => ({
  // Per-state slice of backend-mirrored values.
  state: {},
  // Per-state dispatcher functions (state slice -> (delta) => void).
  dispatch: {},
  // Event-loop adapter set by the React/Astro entrypoint.
  eventLoop: initialEventLoop,
  // File uploads, keyed by upload component id.
  uploads: {},
  // Resolved color mode plus its setters.
  colorMode: initialColorMode,

  // Apply an atomic backend delta. `delta` is `{ [stateName]: partial }`.
  // One `set` call so subscribers see exactly one commit per delta.
  applyDelta: (delta) =>
    set((prev) => {
      const next = { ...prev.state };
      for (const stateName of Object.keys(delta || {})) {
        const patch = delta[stateName];
        if (patch == null) continue;
        next[stateName] = { ...(prev.state[stateName] || {}), ...patch };
      }
      return { state: next };
    }),

  // Replace a state slice in full (used by HYDRATE).
  setStateSlice: (stateName, value) =>
    set((prev) => ({ state: { ...prev.state, [stateName]: value } })),

  // Register a per-state dispatcher (typically wired by the legacy reducer
  // shim in `context.js`).
  registerDispatch: (stateName, fn) =>
    set((prev) => ({ dispatch: { ...prev.dispatch, [stateName]: fn } })),

  // Replace the event-loop slice (the Astro entrypoint calls this once per
  // page; the React Router shim calls it inside `useEventLoop`).
  setEventLoop: (eventLoop) => set({ eventLoop }),

  // Update an upload slot.
  setUploads: (componentId, files) =>
    set((prev) => ({
      uploads: { ...prev.uploads, [componentId]: files },
    })),

  clearUploads: (componentId) =>
    set((prev) => {
      const next = { ...prev.uploads };
      delete next[componentId];
      return { uploads: next };
    }),

  setColorMode: (colorMode) => set({ colorMode }),
}));

// ---------------------------------------------------------------------------
// Helper hooks. These match the ergonomics of the legacy React Context API.
// ---------------------------------------------------------------------------

export const useReflexState = (stateName) =>
  useReflexStore((s) => s.state[stateName]);

export const useReflexDispatch = (stateName) =>
  useReflexStore((s) => s.dispatch[stateName]);

export const useReflexEventLoop = () =>
  useReflexStore((s) => s.eventLoop);

export const useReflexUploads = (componentId) =>
  useReflexStore((s) => s.uploads[componentId] || []);

export const useReflexColorMode = () =>
  useReflexStore((s) => s.colorMode);

// Imperative accessors (for code that runs outside React, e.g. the Astro
// runtime adapter or the event-loop singleton).
export const getReflexState = (stateName) =>
  useReflexStore.getState().state[stateName];

export const getReflexDispatch = (stateName) =>
  useReflexStore.getState().dispatch[stateName];

export const applyReflexDelta = (delta) =>
  useReflexStore.getState().applyDelta(delta);

export const setReflexEventLoop = (eventLoop) =>
  useReflexStore.getState().setEventLoop(eventLoop);

export const registerReflexDispatch = (stateName, fn) =>
  useReflexStore.getState().registerDispatch(stateName, fn);
"""


def event_loop_runtime_template() -> str:
    """Render ``$/utils/event_loop.js`` — the target-agnostic event loop adapter.

    The runtime piece exposes a ``createEventLoop(...)`` factory plus a
    module-singleton ``getOrCreateEventLoop(...)`` accessor. The React Router
    target wraps it inside the existing ``useEventLoop`` hook (compatibility
    shell), and the Astro adapter calls it directly when the first stateful
    island hydrates.

    The implementation here is intentionally minimal: it owns the addEvents
    queue and the connectErrors list, and it pushes its slice into the
    shared Zustand store via ``setReflexEventLoop`` so subscribers stay in
    sync. Socket.io wiring still lives in ``state.js``; that module is
    expected to register itself by calling ``setEventLoopAdapter`` once on
    boot. This split lets us extract the rest of ``state.js`` incrementally
    without breaking the React Router target.

    Returns:
        The full ``event_loop.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
//
// Target-agnostic event loop runtime. Owns the addEvents queue, connect
// errors, and hydration flag; the underlying socket lifecycle lives in
// `state.js` (legacy) and registers via `setEventLoopAdapter`.
import {
  applyReflexDelta,
  setReflexEventLoop,
  useReflexStore,
} from "$/utils/store";

let _adapter = {
  addEvents: undefined,
  connectErrors: [],
  isHydrated: false,
};

const _publish = () => {
  setReflexEventLoop({
    addEvents: _adapter.addEvents,
    connectErrors: [..._adapter.connectErrors],
    isHydrated: _adapter.isHydrated,
  });
};

export const setEventLoopAdapter = (next) => {
  _adapter = { ..._adapter, ...next };
  _publish();
};

export const getEventLoopAdapter = () => _adapter;

// Imperative entry the Astro runtime singleton uses to dispatch a chain.
export const dispatchEventChain = (events) => {
  const fn = _adapter.addEvents;
  if (typeof fn !== "function") {
    // Queue inside the adapter until the socket layer has registered its
    // addEvents implementation.
    _adapter.connectErrors = [
      ..._adapter.connectErrors,
      { type: "queue", reason: "no addEvents adapter yet" },
    ];
    _publish();
    return;
  }
  fn(events);
};

// Convenience re-exports so a single module covers both the store and the
// event-loop in callers that need both.
export { applyReflexDelta, useReflexStore };
"""


def color_mode_inline_setter_template() -> str:
    """Render the ``$/utils/color_mode_inline.js`` head-script helper.

    Used by both targets when generating the inline ``<head>`` script that
    sets the color mode before first paint. Mirrors the Astro layout's
    inline emitter but lives at the Reflex runtime layer so the React
    Router target's `app.html` template can include it too once the React
    runtime stops doing the work itself.

    Returns:
        The full ``color_mode_inline.js`` source.
    """
    return r"""// Generated by Reflex. Do not edit.
// Synchronous inline head script. Resolves cookie -> localStorage ->
// system preference -> default and applies the color mode to <html>
// before first paint.
export const colorModeInlineScript = ({
  cookieName = "reflex-color-mode",
  storageKey = "color_mode",
  defaultColorMode = "system",
} = {}) => `(function () {
  try {
    var resolved = null;
    var match = document.cookie.match(new RegExp('(^|;\\s*)' + ${JSON.stringify(cookieName)} + '=([^;]+)'));
    if (match) { resolved = decodeURIComponent(match[2]); }
    if (!resolved) {
      try {
        var stored = window.localStorage.getItem(${JSON.stringify(storageKey)});
        if (stored) { resolved = stored; }
      } catch (e) {}
    }
    if (!resolved || resolved === 'system') {
      var fallback = ${JSON.stringify(defaultColorMode)};
      if (fallback === 'system') {
        resolved = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
      } else {
        resolved = fallback;
      }
    }
    var root = document.documentElement;
    if (resolved === 'dark') { root.classList.add('dark'); root.classList.remove('light'); }
    else { root.classList.add('light'); root.classList.remove('dark'); }
    root.setAttribute('data-color-mode', resolved);
  } catch (e) {}
})();`;
"""
