"""Generate Reflex source code from a notebook runtime.

The Phase 1 codegen produces a self-contained ``app.py`` skeleton that mirrors the widget
and output structure recorded by the runtime. It is intentionally simple: each widget
becomes a State field with an event handler, and each cell's outputs are placed in the
order they were produced. The generated code is the on-ramp into the full Reflex
framework — a starting point a user can customize, not a perfect transpilation of arbitrary
notebook code.
"""

from __future__ import annotations

import datetime as _dt
import re
from typing import Any

from reflex.notebook.runtime import (
    CellRecord,
    NotebookRuntime,
    OutputRecord,
    WidgetRecord,
)

_INDENT = "    "

_KIND_TO_TYPE: dict[str, str] = {
    "select": "str",
    "slider": "float",
    "text_input": "str",
    "checkbox": "bool",
    "date_picker": "str",
    "file_upload": "str",
    "button": "int",
}

_KIND_TO_COMPONENT: dict[str, str] = {
    "select": "rx.select",
    "slider": "rx.slider",
    "text_input": "rx.input",
    "checkbox": "rx.checkbox",
    "date_picker": "rx.input",
    "file_upload": "rx.upload",
    "button": "rx.button",
}


def generate_app_source(
    runtime: NotebookRuntime, app_name: str = "notebook_app"
) -> str:
    """Generate a Reflex ``app.py`` source string from a runtime snapshot.

    Args:
        runtime: The notebook runtime with recorded cells, widgets, and outputs.
        app_name: A slug used in the generated file's title.

    Returns:
        Python source code for a runnable Reflex app.
    """
    widgets = runtime.widgets
    outputs = runtime.outputs
    cells = runtime.cells
    sanitized = _sanitize_name(app_name)
    state_lines = _emit_state(widgets)
    page_lines = _emit_page(widgets, outputs, cells)
    header = _emit_header(sanitized)
    return "\n".join([
        header,
        "",
        *state_lines,
        "",
        *page_lines,
        "",
        _emit_app(sanitized),
    ])


def _emit_header(app_name: str) -> str:
    """Emit the file header (docstring + imports).

    Args:
        app_name: The slug of the generated app (used in the file docstring).

    Returns:
        Source text containing the docstring and imports.
    """
    return (
        f'"""Auto-generated by Reflex Notebooks on {_dt.datetime.now().isoformat(timespec="seconds")}.\n\n'
        f"This is a starting point. Edit freely — once you check it in you have a normal Reflex app.\n"
        f'"""\n\n'
        "from __future__ import annotations\n\n"
        "import reflex as rx\n"
    )


def _emit_state(widgets: list[WidgetRecord]) -> list[str]:
    """Emit the State class for the generated app.

    Args:
        widgets: All widgets registered with the runtime.

    Returns:
        Source lines for the generated ``State`` class.
    """
    lines = [
        "class State(rx.State):",
        f'{_INDENT}"""Notebook state derived from input widgets."""',
        "",
    ]
    if not widgets:
        lines.append(f"{_INDENT}pass")
        return lines
    seen_names: set[str] = set()
    for widget in widgets:
        name = _widget_field_name(widget, seen_names)
        widget._gen_field = name  # type: ignore[attr-defined]
        py_type = _KIND_TO_TYPE.get(widget.kind, "str")
        default = _format_default(widget)
        lines.append(f"{_INDENT}{name}: {py_type} = {default}")
    lines.append("")
    for widget in widgets:
        name = widget._gen_field  # type: ignore[attr-defined]
        py_type = _KIND_TO_TYPE.get(widget.kind, "str")
        lines.extend([
            f"{_INDENT}@rx.event",
            f"{_INDENT}def set_{name}(self, value: {py_type}):",
            f'{_INDENT * 2}"""Update {name} from the bound widget."""',
            f"{_INDENT * 2}self.{name} = value",
            "",
        ])
    return lines


def _emit_page(
    widgets: list[WidgetRecord],
    outputs: list[OutputRecord],
    cells: list[CellRecord],
) -> list[str]:
    """Emit the page() function that lays out widgets and outputs.

    Args:
        widgets: All registered widgets.
        outputs: All recorded outputs.
        cells: All recorded cells (used to preserve execution order).

    Returns:
        Source lines for the generated ``index`` function.
    """
    lines = [
        "def index() -> rx.Component:",
        f'{_INDENT}"""The deployed notebook page."""',
        f"{_INDENT}return rx.vstack(",
    ]
    widgets_by_cell: dict[int, list[WidgetRecord]] = {}
    for widget in widgets:
        widgets_by_cell.setdefault(widget.cell_position, []).append(widget)
    outputs_by_cell: dict[int, list[OutputRecord]] = {}
    for output in outputs:
        outputs_by_cell.setdefault(output.cell_position, []).append(output)
    cell_positions = sorted(
        {c.position for c in cells} | set(widgets_by_cell) | set(outputs_by_cell)
    )
    for position in cell_positions:
        for widget in widgets_by_cell.get(position, []):
            code, note = _emit_widget_component(widget)
            lines.append(_indent_with_note(code, note))
        for output in outputs_by_cell.get(position, []):
            code, note = _emit_output_component(output)
            lines.append(_indent_with_note(code, note))
    lines.extend([
        f'{_INDENT * 2}spacing="4",',
        f'{_INDENT * 2}padding="2em",',
        f"{_INDENT})",
    ])
    return lines


def _emit_widget_component(widget: WidgetRecord) -> tuple[str, str]:
    """Emit a Reflex component call for a single widget.

    Returns:
        A pair of ``(code, note)`` where ``note`` is an inline comment to attach.
    """
    name = getattr(widget, "_gen_field", _widget_field_name(widget, set()))
    component = _KIND_TO_COMPONENT.get(widget.kind, "rx.input")
    bind = f"value=State.{name}, on_change=State.set_{name}"
    label = widget.label or widget.kind.replace("_", " ").title()
    if widget.kind == "select":
        choices = widget.options.get("choices", [])
        return f"{component}({choices!r}, {bind}, placeholder={label!r})", ""
    if widget.kind == "slider":
        slider_call = (
            f"{component}({bind}, "
            f"min={widget.options.get('min', 0)}, "
            f"max={widget.options.get('max', 100)}, "
            f"step={widget.options.get('step', 1)})"
        )
        return slider_call, ""
    if widget.kind == "text_input":
        placeholder = widget.options.get("placeholder", "") or label
        return f"{component}({bind}, placeholder={placeholder!r})", ""
    if widget.kind == "checkbox":
        return (
            f"{component}({label!r}, checked=State.{name}, on_change=State.set_{name})",
            "",
        )
    if widget.kind == "date_picker":
        return f'{component}(type="date", {bind})', ""
    if widget.kind == "file_upload":
        return f"rx.upload(rx.text({label!r}), id={name!r})", ""
    if widget.kind == "button":
        return (
            f"{component}({label!r}, on_click=State.set_{name}(State.{name} + 1))",
            "",
        )
    return f"rx.text({label!r})", ""


def _emit_output_component(output: OutputRecord) -> tuple[str, str]:
    """Emit a Reflex component call for a single recorded output.

    Returns:
        A pair of ``(code, note)`` where ``note`` is an inline comment to attach.
    """
    if output.kind == "primitive":
        return "rx.text('')", f"primitive output: {output.repr_hint}"
    if output.kind == "dataframe":
        return "rx.data_table()", f"placeholder for {output.repr_hint}"
    if output.kind == "matplotlib":
        return "rx.image(src='')", "placeholder for matplotlib figure"
    if output.kind == "plotly":
        return "rx.plotly()", "placeholder for plotly figure"
    if output.kind == "html":
        return "rx.html('')", "placeholder for HTML output"
    if output.kind == "row":
        items = (
            [k for k in output.repr_hint.split(",") if k] if output.repr_hint else []
        )
        children = ", ".join("rx.box()" for _ in items) or "rx.box()"
        note = f"row of {','.join(items)}" if items else "row"
        return f"rx.hstack({children})", note
    return "rx.box()", "unsupported output"


def _indent_with_note(code: str, note: str) -> str:
    """Indent a component call and append an optional inline comment after the trailing comma.

    Args:
        code: The component call source.
        note: Optional inline comment, attached after the trailing comma.

    Returns:
        A correctly indented and commented source line.
    """
    base = f"{_INDENT * 2}{code},"
    if note:
        return f"{base}  # {note}"
    return base


def _emit_app(app_name: str) -> str:
    """Emit the trailing app construction.

    Args:
        app_name: The slug used for the page title.

    Returns:
        Source text creating the ``app`` and registering ``index``.
    """
    return f"app = rx.App()\napp.add_page(index, title={app_name!r})\n"


def _widget_field_name(widget: WidgetRecord, seen: set[str]) -> str:
    """Generate a Python identifier for a widget, ensuring no collisions in ``seen``.

    Args:
        widget: The widget to derive the field name from.
        seen: A set of previously chosen names; mutated to include the result.

    Returns:
        A unique Python identifier suitable for a State field.
    """
    base = _slug(widget.label) if widget.label else widget.kind
    candidate = base
    counter = 2
    while candidate in seen:
        candidate = f"{base}_{counter}"
        counter += 1
    seen.add(candidate)
    return candidate


def _format_default(widget: WidgetRecord) -> str:
    """Format a widget's current value as a Python literal for the State class.

    Args:
        widget: The widget whose value should be serialized.

    Returns:
        A Python literal expression that reproduces the widget's current value.
    """
    if widget.kind == "date_picker":
        return repr(str(widget.value)) if widget.value is not None else '""'
    if widget.kind == "file_upload":
        return '""'
    if widget.kind == "button":
        return "0"
    return repr(widget.value)


_SLUG_RE = re.compile(r"[^a-zA-Z0-9_]+")


def _slug(text: str) -> str:
    """Convert arbitrary text into a snake_case Python identifier.

    Args:
        text: The raw text to slugify.

    Returns:
        A safe Python identifier; ``"field"`` if the input has no alphanumerics.
    """
    cleaned = _SLUG_RE.sub("_", text.strip().lower()).strip("_")
    if not cleaned:
        return "field"
    if cleaned[0].isdigit():
        cleaned = f"f_{cleaned}"
    return cleaned


def _sanitize_name(name: str) -> str:
    """Sanitize an arbitrary app name for use as a Python identifier.

    Args:
        name: The raw app name.

    Returns:
        A safe Python identifier slug.
    """
    return _slug(name) or "notebook_app"


def to_widget_summary(widget: WidgetRecord) -> dict[str, Any]:
    """Return a JSON-friendly summary of a widget (used by tests and tooling).

    Args:
        widget: The widget record to summarize.

    Returns:
        A dict containing the widget's key fields.
    """
    return {
        "key": widget.key,
        "kind": widget.kind,
        "label": widget.label,
        "value": widget.value,
        "options": widget.options,
        "cell_position": widget.cell_position,
    }
